import os

from dotenv import load_dotenv

load_dotenv()

DATA_MODE = os.getenv("MCP_DATA_MODE", "mock")

ANTHROPIC_API_KEY = os.getenv("ANTHROPIC_API_KEY", "")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")

AZURE_AI_SEARCH_ENDPOINT = os.getenv("AZURE_AI_SEARCH_ENDPOINT", "")
AZURE_AI_SEARCH_KEY = os.getenv("AZURE_AI_SEARCH_KEY", "")
AZURE_AI_SEARCH_INDEX = os.getenv("AZURE_AI_SEARCH_INDEX", "enterprise-knowledge")

DATAVERSE_URL = os.getenv("DATAVERSE_URL", "")
DATAVERSE_SP_CLIENT_ID = os.getenv("DATAVERSE_SP_CLIENT_ID", "")
DATAVERSE_SP_CLIENT_SECRET = os.getenv("DATAVERSE_SP_CLIENT_SECRET", "")
DATAVERSE_SP_TENANT_ID = os.getenv("DATAVERSE_SP_TENANT_ID", "")

POWER_AUTOMATE_APPROVAL_URL = os.getenv("POWER_AUTOMATE_APPROVAL_URL", "")
APPLICATION_INSIGHTS_CONNECTION_STRING = os.getenv(
    "APPLICATION_INSIGHTS_CONNECTION_STRING", ""
)
